"""Fase 1 - maestras: productores, mercados, binders

Revision ID: 02f3183ccd0d
Revises: 
Create Date: 2026-06-15 15:56:03.918781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02f3183ccd0d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('umr', sa.String(length=120), nullable=True),
    sa.Column('agreement_number', sa.String(length=120), nullable=True),
    sa.Column('referencia_bar', sa.String(length=120), nullable=True),
    sa.Column('coverholder', sa.String(length=255), nullable=True),
    sa.Column('mercado', sa.String(length=255), nullable=True),
    sa.Column('fecha_efecto', sa.Date(), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=60), nullable=True),
    sa.Column('yoa', sa.String(length=20), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('limite_primas', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('comision', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('comision_retenida', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('profit_commission', sa.Boolean(), nullable=False),
    sa.Column('gwp', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('netto_uw', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('number_policies', sa.Integer(), nullable=True),
    sa.Column('ramo', sa.String(length=120), nullable=True),
    sa.Column('numero_secciones', sa.Integer(), nullable=True),
    sa.Column('ramo_seccion1', sa.String(length=120), nullable=True),
    sa.Column('ramo_seccion2', sa.String(length=120), nullable=True),
    sa.Column('ramo_seccion3', sa.String(length=120), nullable=True),
    sa.Column('ramo_seccion4', sa.String(length=120), nullable=True),
    sa.Column('intervalo_risk', sa.String(length=60), nullable=True),
    sa.Column('plazo_envio_risk', sa.String(length=60), nullable=True),
    sa.Column('intervalo_premium', sa.String(length=60), nullable=True),
    sa.Column('plazo_envio_premium', sa.String(length=60), nullable=True),
    sa.Column('intervalo_claims', sa.String(length=60), nullable=True),
    sa.Column('plazo_envio_claims', sa.String(length=60), nullable=True),
    sa.Column('plazo_pago', sa.String(length=60), nullable=True),
    sa.Column('cuenta', sa.String(length=120), nullable=True),
    sa.Column('claims_bdx', sa.String(length=120), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_binders_titulo'), 'binders', ['titulo'], unique=False)
    op.create_index(op.f('ix_binders_umr'), 'binders', ['umr'], unique=False)
    op.create_table('mercados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sp_old_id', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('id_tipo', sa.Integer(), nullable=True),
    sa.Column('tipo_mercado', sa.String(length=120), nullable=True),
    sa.Column('mercado', sa.String(length=255), nullable=True),
    sa.Column('toba', sa.Boolean(), nullable=False),
    sa.Column('risk', sa.String(length=120), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mercados_codigo'), 'mercados', ['codigo'], unique=False)
    op.create_index(op.f('ix_mercados_nombre'), 'mercados', ['nombre'], unique=False)
    op.create_index(op.f('ix_mercados_sp_old_id'), 'mercados', ['sp_old_id'], unique=False)
    op.create_table('productores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sp_old_id', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Integer(), nullable=True),
    sa.Column('es_coverholder', sa.Boolean(), nullable=False),
    sa.Column('cif', sa.String(length=50), nullable=True),
    sa.Column('domicilio', sa.String(length=255), nullable=True),
    sa.Column('codigo_postal', sa.String(length=20), nullable=True),
    sa.Column('localidad', sa.String(length=120), nullable=True),
    sa.Column('provincia', sa.String(length=120), nullable=True),
    sa.Column('pais', sa.String(length=120), nullable=True),
    sa.Column('contacto', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=60), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productores_codigo'), 'productores', ['codigo'], unique=False)
    op.create_index(op.f('ix_productores_nombre'), 'productores', ['nombre'], unique=False)
    op.create_index(op.f('ix_productores_sp_old_id'), 'productores', ['sp_old_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_productores_sp_old_id'), table_name='productores')
    op.drop_index(op.f('ix_productores_nombre'), table_name='productores')
    op.drop_index(op.f('ix_productores_codigo'), table_name='productores')
    op.drop_table('productores')
    op.drop_index(op.f('ix_mercados_sp_old_id'), table_name='mercados')
    op.drop_index(op.f('ix_mercados_nombre'), table_name='mercados')
    op.drop_index(op.f('ix_mercados_codigo'), table_name='mercados')
    op.drop_table('mercados')
    op.drop_index(op.f('ix_binders_umr'), table_name='binders')
    op.drop_index(op.f('ix_binders_titulo'), table_name='binders')
    op.drop_table('binders')
    # ### end Alembic commands ###
