"""seccion: notificacion y sujeto_pc

Revision ID: 0d7f9af6233a
Revises: 19a30faf6375
Create Date: 2026-06-16 12:11:46.403508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d7f9af6233a'
down_revision: Union[str, Sequence[str], None] = '19a30faf6375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('binder_secciones', sa.Column('notificacion', sa.Numeric(precision=7, scale=4), nullable=True))
    op.add_column('binder_secciones', sa.Column('sujeto_pc', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('binder_secciones', 'sujeto_pc')
    op.drop_column('binder_secciones', 'notificacion')
    # ### end Alembic commands ###
