"""seccion: varios risk codes

Revision ID: 19a30faf6375
Revises: e00cb989d5d9
Create Date: 2026-06-15 23:58:41.264171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19a30faf6375'
down_revision: Union[str, Sequence[str], None] = 'e00cb989d5d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seccion_risk_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seccion_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['seccion_id'], ['binder_secciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seccion_risk_codes_seccion_id'), 'seccion_risk_codes', ['seccion_id'], unique=False)
    op.drop_column('binder_secciones', 'risk_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('binder_secciones', sa.Column('risk_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_seccion_risk_codes_seccion_id'), table_name='seccion_risk_codes')
    op.drop_table('seccion_risk_codes')
    # ### end Alembic commands ###
