"""cuenta_bancaria categoria

Revision ID: 247c0b7850e4
Revises: 821b6306b83b
Create Date: 2026-06-16 15:27:44.960494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '247c0b7850e4'
down_revision: Union[str, Sequence[str], None] = '821b6306b83b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cuentas_bancarias', sa.Column('categoria', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cuentas_bancarias', 'categoria')
    # ### end Alembic commands ###
