"""binder: datos comunes (profit commission, bdx, comision mayrit, cuenta) + tabla cuentas_bancarias

Revision ID: 2cf10c066d9a
Revises: 0d7f9af6233a
Create Date: 2026-06-16 12:35:56.061842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cf10c066d9a'
down_revision: Union[str, Sequence[str], None] = '0d7f9af6233a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuentas_bancarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sp_old_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('banco', sa.String(length=160), nullable=True),
    sa.Column('titular', sa.String(length=160), nullable=True),
    sa.Column('iban', sa.String(length=40), nullable=True),
    sa.Column('swift_bic', sa.String(length=20), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuentas_bancarias_sp_old_id'), 'cuentas_bancarias', ['sp_old_id'], unique=False)
    op.add_column('binders', sa.Column('profit_commission', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('binders', sa.Column('pc_porcentaje', sa.Numeric(precision=7, scale=4), nullable=True))
    op.add_column('binders', sa.Column('pc_gastos', sa.Numeric(precision=7, scale=4), nullable=True))
    op.add_column('binders', sa.Column('risk_bdx_intervalo', sa.String(length=20), nullable=True))
    op.add_column('binders', sa.Column('risk_bdx_plazo', sa.Integer(), nullable=True))
    op.add_column('binders', sa.Column('premium_bdx_intervalo', sa.String(length=20), nullable=True))
    op.add_column('binders', sa.Column('premium_bdx_plazo', sa.Integer(), nullable=True))
    op.add_column('binders', sa.Column('claims_bdx_intervalo', sa.String(length=20), nullable=True))
    op.add_column('binders', sa.Column('claims_bdx_plazo', sa.Integer(), nullable=True))
    op.add_column('binders', sa.Column('comision_mayrit', sa.Numeric(precision=7, scale=4), nullable=True))
    op.add_column('binders', sa.Column('cuenta_bancaria_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'binders', 'cuentas_bancarias', ['cuenta_bancaria_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'binders', type_='foreignkey')
    op.drop_column('binders', 'cuenta_bancaria_id')
    op.drop_column('binders', 'comision_mayrit')
    op.drop_column('binders', 'claims_bdx_plazo')
    op.drop_column('binders', 'claims_bdx_intervalo')
    op.drop_column('binders', 'premium_bdx_plazo')
    op.drop_column('binders', 'premium_bdx_intervalo')
    op.drop_column('binders', 'risk_bdx_plazo')
    op.drop_column('binders', 'risk_bdx_intervalo')
    op.drop_column('binders', 'pc_gastos')
    op.drop_column('binders', 'pc_porcentaje')
    op.drop_column('binders', 'profit_commission')
    op.drop_index(op.f('ix_cuentas_bancarias_sp_old_id'), table_name='cuentas_bancarias')
    op.drop_table('cuentas_bancarias')
    # ### end Alembic commands ###
