"""binders: quitar referencia (UMR es el identificador)

Revision ID: 387029767c8d
Revises: 710d069793f0
Create Date: 2026-06-15 22:56:13.485602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '387029767c8d'
down_revision: Union[str, Sequence[str], None] = '710d069793f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_binders_referencia'), table_name='binders')
    op.create_index(op.f('ix_binders_agreement_number'), 'binders', ['agreement_number'], unique=False)
    op.drop_column('binders', 'referencia')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('binders', sa.Column('referencia', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_binders_agreement_number'), table_name='binders')
    op.create_index(op.f('ix_binders_referencia'), 'binders', ['referencia'], unique=False)
    # ### end Alembic commands ###
