"""risk codes por ramo

Revision ID: 46547a36c026
Revises: f1e5485d1802
Create Date: 2026-06-15 23:40:09.269671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46547a36c026'
down_revision: Union[str, Sequence[str], None] = 'f1e5485d1802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ramo_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['ramo_id'], ['ramos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_codes_codigo'), 'risk_codes', ['codigo'], unique=True)
    op.create_index(op.f('ix_risk_codes_ramo_id'), 'risk_codes', ['ramo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_codes_ramo_id'), table_name='risk_codes')
    op.drop_index(op.f('ix_risk_codes_codigo'), table_name='risk_codes')
    op.drop_table('risk_codes')
    # ### end Alembic commands ###
