"""crear tabla tomadores

Revision ID: 5851f91f8539
Revises: a36ac2d22ba9
Create Date: 2026-06-15 20:14:44.272786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5851f91f8539'
down_revision: Union[str, Sequence[str], None] = 'a36ac2d22ba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tomadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sp_old_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=True),
    sa.Column('cif', sa.String(length=50), nullable=True),
    sa.Column('domicilio', sa.String(length=255), nullable=True),
    sa.Column('codigo_postal', sa.String(length=20), nullable=True),
    sa.Column('localidad', sa.String(length=120), nullable=True),
    sa.Column('provincia', sa.String(length=120), nullable=True),
    sa.Column('pais', sa.String(length=120), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tomadores_cif'), 'tomadores', ['cif'], unique=False)
    op.create_index(op.f('ix_tomadores_nombre'), 'tomadores', ['nombre'], unique=False)
    op.create_index(op.f('ix_tomadores_sp_old_id'), 'tomadores', ['sp_old_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tomadores_sp_old_id'), table_name='tomadores')
    op.drop_index(op.f('ix_tomadores_nombre'), table_name='tomadores')
    op.drop_index(op.f('ix_tomadores_cif'), table_name='tomadores')
    op.drop_table('tomadores')
    # ### end Alembic commands ###
