"""binders: rediseno con secciones y mercados por seccion

Revision ID: 710d069793f0
Revises: 80ba5368a47a
Create Date: 2026-06-15 22:40:33.626400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '710d069793f0'
down_revision: Union[str, Sequence[str], None] = '80ba5368a47a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binder_secciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('binder_id', sa.Integer(), nullable=False),
    sa.Column('ramo', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['binder_id'], ['binders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_binder_secciones_binder_id'), 'binder_secciones', ['binder_id'], unique=False)
    op.create_table('seccion_mercados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seccion_id', sa.Integer(), nullable=False),
    sa.Column('mercado_id', sa.Integer(), nullable=False),
    sa.Column('participacion', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['mercado_id'], ['mercados.id'], ),
    sa.ForeignKeyConstraint(['seccion_id'], ['binder_secciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seccion_mercados_seccion_id'), 'seccion_mercados', ['seccion_id'], unique=False)
    op.add_column('binders', sa.Column('sp_old_id', sa.Integer(), nullable=True))
    op.add_column('binders', sa.Column('referencia', sa.String(length=120), nullable=False))
    op.add_column('binders', sa.Column('productor_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_binders_titulo'), table_name='binders')
    op.create_index(op.f('ix_binders_referencia'), 'binders', ['referencia'], unique=False)
    op.create_index(op.f('ix_binders_sp_old_id'), 'binders', ['sp_old_id'], unique=False)
    op.create_foreign_key(None, 'binders', 'productores', ['productor_id'], ['id'])
    op.drop_column('binders', 'ramo_seccion1')
    op.drop_column('binders', 'coverholder')
    op.drop_column('binders', 'plazo_pago')
    op.drop_column('binders', 'ramo_seccion2')
    op.drop_column('binders', 'plazo_envio_claims')
    op.drop_column('binders', 'plazo_envio_premium')
    op.drop_column('binders', 'plazo_envio_risk')
    op.drop_column('binders', 'referencia_bar')
    op.drop_column('binders', 'profit_commission')
    op.drop_column('binders', 'comision_retenida')
    op.drop_column('binders', 'ramo')
    op.drop_column('binders', 'number_policies')
    op.drop_column('binders', 'cuenta')
    op.drop_column('binders', 'gwp')
    op.drop_column('binders', 'numero_secciones')
    op.drop_column('binders', 'netto_uw')
    op.drop_column('binders', 'ramo_seccion4')
    op.drop_column('binders', 'intervalo_risk')
    op.drop_column('binders', 'mercado')
    op.drop_column('binders', 'claims_bdx')
    op.drop_column('binders', 'titulo')
    op.drop_column('binders', 'intervalo_claims')
    op.drop_column('binders', 'ramo_seccion3')
    op.drop_column('binders', 'intervalo_premium')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('binders', sa.Column('intervalo_premium', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.add_column('binders', sa.Column('ramo_seccion3', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('binders', sa.Column('intervalo_claims', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.add_column('binders', sa.Column('titulo', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('binders', sa.Column('claims_bdx', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('binders', sa.Column('mercado', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('binders', sa.Column('intervalo_risk', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.add_column('binders', sa.Column('ramo_seccion4', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('binders', sa.Column('netto_uw', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True))
    op.add_column('binders', sa.Column('numero_secciones', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('binders', sa.Column('gwp', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True))
    op.add_column('binders', sa.Column('cuenta', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('binders', sa.Column('number_policies', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('binders', sa.Column('ramo', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('binders', sa.Column('comision_retenida', sa.NUMERIC(precision=7, scale=4), autoincrement=False, nullable=True))
    op.add_column('binders', sa.Column('profit_commission', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('binders', sa.Column('referencia_bar', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('binders', sa.Column('plazo_envio_risk', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.add_column('binders', sa.Column('plazo_envio_premium', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.add_column('binders', sa.Column('plazo_envio_claims', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.add_column('binders', sa.Column('ramo_seccion2', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('binders', sa.Column('plazo_pago', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.add_column('binders', sa.Column('coverholder', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('binders', sa.Column('ramo_seccion1', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'binders', type_='foreignkey')
    op.drop_index(op.f('ix_binders_sp_old_id'), table_name='binders')
    op.drop_index(op.f('ix_binders_referencia'), table_name='binders')
    op.create_index(op.f('ix_binders_titulo'), 'binders', ['titulo'], unique=False)
    op.drop_column('binders', 'productor_id')
    op.drop_column('binders', 'referencia')
    op.drop_column('binders', 'sp_old_id')
    op.drop_index(op.f('ix_seccion_mercados_seccion_id'), table_name='seccion_mercados')
    op.drop_table('seccion_mercados')
    op.drop_index(op.f('ix_binder_secciones_binder_id'), table_name='binder_secciones')
    op.drop_table('binder_secciones')
    # ### end Alembic commands ###
