"""productores: quitar es_coverholder, anadir persona

Revision ID: 76ea4b50d1b1
Revises: 5851f91f8539
Create Date: 2026-06-15 21:41:23.531085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76ea4b50d1b1'
down_revision: Union[str, Sequence[str], None] = '5851f91f8539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productores', sa.Column('persona', sa.String(length=20), nullable=True))
    op.drop_column('productores', 'es_coverholder')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productores', sa.Column('es_coverholder', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('productores', 'persona')
    # ### end Alembic commands ###
