"""tomadores: quitar alias

Revision ID: 80ba5368a47a
Revises: 565ebecb10e5
Create Date: 2026-06-15 22:22:31.650982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80ba5368a47a'
down_revision: Union[str, Sequence[str], None] = '565ebecb10e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_productores_codigo'), table_name='productores')
    op.create_index(op.f('ix_productores_alias'), 'productores', ['alias'], unique=False)
    op.drop_column('tomadores', 'alias')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tomadores', sa.Column('alias', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_productores_alias'), table_name='productores')
    op.create_index(op.f('ix_productores_codigo'), 'productores', ['alias'], unique=False)
    # ### end Alembic commands ###
