"""cuenta_bancaria activa

Revision ID: 821b6306b83b
Revises: bbb6c494b043
Create Date: 2026-06-16 15:02:20.850059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '821b6306b83b'
down_revision: Union[str, Sequence[str], None] = 'bbb6c494b043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cuentas_bancarias', sa.Column('activa', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cuentas_bancarias', 'activa')
    # ### end Alembic commands ###
