"""productores: quitar contacto, telefono y numero

Revision ID: a36ac2d22ba9
Revises: e622421bc9e8
Create Date: 2026-06-15 20:10:15.142214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a36ac2d22ba9'
down_revision: Union[str, Sequence[str], None] = 'e622421bc9e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productores', 'telefono')
    op.drop_column('productores', 'numero')
    op.drop_column('productores', 'contacto')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productores', sa.Column('contacto', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('productores', sa.Column('numero', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('productores', sa.Column('telefono', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
