"""bdx risk/premium: cabecera y lineas

Revision ID: a8ec1d2b6f7e
Revises: 247c0b7850e4
Create Date: 2026-06-16 15:48:06.868844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8ec1d2b6f7e'
down_revision: Union[str, Sequence[str], None] = '247c0b7850e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bdx',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('binder_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('reporting_period_start', sa.Date(), nullable=True),
    sa.Column('reporting_period_end', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=40), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['binder_id'], ['binders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bdx_binder_id'), 'bdx', ['binder_id'], unique=False)
    op.create_table('bdx_lineas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sp_old_id', sa.Integer(), nullable=True),
    sa.Column('bdx_id', sa.Integer(), nullable=False),
    sa.Column('section_no', sa.Integer(), nullable=True),
    sa.Column('class_of_business', sa.String(length=120), nullable=True),
    sa.Column('risk_code', sa.String(length=20), nullable=True),
    sa.Column('type_of_insurance', sa.String(length=40), nullable=True),
    sa.Column('certificate_ref', sa.String(length=120), nullable=True),
    sa.Column('insured_name', sa.String(length=255), nullable=True),
    sa.Column('insured_id', sa.String(length=60), nullable=True),
    sa.Column('insured_address', sa.String(length=255), nullable=True),
    sa.Column('insured_province', sa.String(length=120), nullable=True),
    sa.Column('insured_postcode', sa.String(length=20), nullable=True),
    sa.Column('insured_country', sa.String(length=80), nullable=True),
    sa.Column('risk_inception_date', sa.Date(), nullable=True),
    sa.Column('risk_expiry_date', sa.Date(), nullable=True),
    sa.Column('location_risk_province', sa.String(length=120), nullable=True),
    sa.Column('location_risk_country', sa.String(length=80), nullable=True),
    sa.Column('risk_transaction_type', sa.String(length=40), nullable=True),
    sa.Column('transaction_type', sa.String(length=40), nullable=True),
    sa.Column('effective_date_transaction', sa.Date(), nullable=True),
    sa.Column('expiry_date_transaction', sa.Date(), nullable=True),
    sa.Column('original_currency_premium', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('gross_written_premium', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('written_line_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('total_gwp_our_line', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fees', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('commission_coverholder_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('commission_coverholder_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_taxes_levies', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_gwp_including_tax', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_premium_to_broker', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('sum_insured_currency', sa.String(length=10), nullable=True),
    sa.Column('sum_insured_our_line', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('deductible_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('deductible_basis', sa.String(length=40), nullable=True),
    sa.Column('tax1_jurisdiction', sa.String(length=120), nullable=True),
    sa.Column('tax1_type', sa.String(length=80), nullable=True),
    sa.Column('tax1_taxable_premium', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax1_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('tax1_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax1_administered_by', sa.String(length=80), nullable=True),
    sa.Column('tax1_payable_by', sa.String(length=80), nullable=True),
    sa.Column('tax2_jurisdiction', sa.String(length=120), nullable=True),
    sa.Column('tax2_type', sa.String(length=80), nullable=True),
    sa.Column('tax2_taxable_premium', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax2_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('tax2_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax2_administered_by', sa.String(length=80), nullable=True),
    sa.Column('tax2_payable_by', sa.String(length=80), nullable=True),
    sa.Column('tax3_jurisdiction', sa.String(length=120), nullable=True),
    sa.Column('tax3_type', sa.String(length=80), nullable=True),
    sa.Column('tax3_taxable_premium', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax3_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('tax3_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax3_administered_by', sa.String(length=80), nullable=True),
    sa.Column('tax3_payable_by', sa.String(length=80), nullable=True),
    sa.Column('tax4_jurisdiction', sa.String(length=120), nullable=True),
    sa.Column('tax4_type', sa.String(length=80), nullable=True),
    sa.Column('tax4_taxable_premium', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax4_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('tax4_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax4_administered_by', sa.String(length=80), nullable=True),
    sa.Column('tax4_payable_by', sa.String(length=80), nullable=True),
    sa.Column('instalment_number', sa.Integer(), nullable=True),
    sa.Column('number_of_instalments', sa.Integer(), nullable=True),
    sa.Column('referred_to_london', sa.String(length=10), nullable=True),
    sa.Column('pct_for_lloyds', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('policy_issuance_date', sa.Date(), nullable=True),
    sa.Column('policy_number_reinsured', sa.String(length=120), nullable=True),
    sa.Column('brokerage_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('brokerage_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('final_net_premium_uw', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('prima_cobrada', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ingresado', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('premium_payment_date', sa.Date(), nullable=True),
    sa.Column('traspaso', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('traspasado', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fecha_traspaso', sa.Date(), nullable=True),
    sa.Column('liquidado', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('liquidado_uw', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fecha_liquidacion', sa.Date(), nullable=True),
    sa.Column('recibo', sa.String(length=120), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bdx_id'], ['bdx.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bdx_lineas_bdx_id'), 'bdx_lineas', ['bdx_id'], unique=False)
    op.create_index(op.f('ix_bdx_lineas_sp_old_id'), 'bdx_lineas', ['sp_old_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bdx_lineas_sp_old_id'), table_name='bdx_lineas')
    op.drop_index(op.f('ix_bdx_lineas_bdx_id'), table_name='bdx_lineas')
    op.drop_table('bdx_lineas')
    op.drop_index(op.f('ix_bdx_binder_id'), table_name='bdx')
    op.drop_table('bdx')
    # ### end Alembic commands ###
