"""binder_suplementos: versiones (snapshot) del binder

Revision ID: bbb6c494b043
Revises: 490f3ee3fbb4
Create Date: 2026-06-16 13:42:01.114207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbb6c494b043'
down_revision: Union[str, Sequence[str], None] = '490f3ee3fbb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binder_suplementos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('binder_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('fecha_efecto', sa.Date(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['binder_id'], ['binders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_binder_suplementos_binder_id'), 'binder_suplementos', ['binder_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_binder_suplementos_binder_id'), table_name='binder_suplementos')
    op.drop_table('binder_suplementos')
    # ### end Alembic commands ###
