"""mercados: quitar columnas risk y mercado

Revision ID: bc674cf1f56a
Revises: 02f3183ccd0d
Create Date: 2026-06-15 19:05:05.178629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc674cf1f56a'
down_revision: Union[str, Sequence[str], None] = '02f3183ccd0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mercados', 'mercado')
    op.drop_column('mercados', 'risk')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mercados', sa.Column('risk', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('mercados', sa.Column('mercado', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
