"""seccion: risk_code

Revision ID: e00cb989d5d9
Revises: 46547a36c026
Create Date: 2026-06-15 23:45:48.832052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e00cb989d5d9'
down_revision: Union[str, Sequence[str], None] = '46547a36c026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('binder_secciones', sa.Column('risk_code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('binder_secciones', 'risk_code')
    # ### end Alembic commands ###
