"""productores: tipo a texto

Revision ID: e622421bc9e8
Revises: bc674cf1f56a
Create Date: 2026-06-15 20:02:13.084562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e622421bc9e8'
down_revision: Union[str, Sequence[str], None] = 'bc674cf1f56a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productores', 'tipo',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=40),
               existing_nullable=True,
               postgresql_using='tipo::varchar')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productores', 'tipo',
               existing_type=sa.String(length=40),
               type_=sa.INTEGER(),
               existing_nullable=True,
               postgresql_using='tipo::integer')
    # ### end Alembic commands ###
