"""catalogo de ramos

Revision ID: f1e5485d1802
Revises: f8eab70251f9
Create Date: 2026-06-15 23:14:12.623937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1e5485d1802'
down_revision: Union[str, Sequence[str], None] = 'f8eab70251f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    ramos = op.create_table('ramos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ramos_nombre'), 'ramos', ['nombre'], unique=True)
    # ### end Alembic commands ###

    # Siembra inicial de los 11 ramos (lista 'Mayrit - Ramo' del sistema antiguo).
    op.bulk_insert(
        ramos,
        [
            {"nombre": n}
            for n in [
                "Accidentes Personales",
                "Aviación",
                "Caución",
                "Contingencias",
                "Crédito y Garantía Financiera",
                "Daños Materiales",
                "Fine Art",
                "Livestock",
                "RC General",
                "RC Profesional",
                "Transportes",
            ]
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ramos_nombre'), table_name='ramos')
    op.drop_table('ramos')
    # ### end Alembic commands ###
