"""binder: mover comision y limite_primas a seccion

Revision ID: f8eab70251f9
Revises: 387029767c8d
Create Date: 2026-06-15 23:04:06.215589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8eab70251f9'
down_revision: Union[str, Sequence[str], None] = '387029767c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('binder_secciones', sa.Column('comision', sa.Numeric(precision=7, scale=4), nullable=True))
    op.add_column('binder_secciones', sa.Column('limite_primas', sa.Numeric(precision=18, scale=2), nullable=True))
    op.drop_column('binders', 'limite_primas')
    op.drop_column('binders', 'comision')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('binders', sa.Column('comision', sa.NUMERIC(precision=7, scale=4), autoincrement=False, nullable=True))
    op.add_column('binders', sa.Column('limite_primas', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True))
    op.drop_column('binder_secciones', 'limite_primas')
    op.drop_column('binder_secciones', 'comision')
    # ### end Alembic commands ###
